Update collectstatic

diff --git a/bin/steps/collectstatic b/bin/steps/collectstatic
--- a/bin/steps/collectstatic
+++ b/bin/steps/collectstatic
@@ -1,17 +1,36 @@
 #!/usr/bin/env bash
 
-puts_step "Collecting static files"
+source $BIN_DIR/utils
 
-# Work around Heroku bug whereby pylibmc isn't availble during
-# compile phase. See: https://github.com/heroku/heroku-buildpack-python/issues/57
-export MEMCACHE_SERVERS="" MEMCACHIER_SERVERS=""
+MANAGE_FILE=$(find . -maxdepth 3 -type f -name 'manage.py' | head -1)
+MANAGE_FILE=${MANAGE_FILE:-fakepath}
 
-# Check if collectstatic is configured properly.
-if [ ! "$DISABLE_COLLECTSTATIC_DRYRUN" ]; then
-    echo "Checking configuration..." | indent
-    python manage.py collectstatic --dry-run --noinput >/dev/null
+[ -f .heroku/collectstatic_disabled ] && DISABLE_COLLECTSTATIC=1
+
+bpwatch start collectstatic
+
+if [ ! "$DISABLE_COLLECTSTATIC" ] && [ -f "$MANAGE_FILE" ]; then
+    set +e
+
+    echo "-----> Preparing static assets"
+    # Check if collectstatic is configured properly.
+    python $MANAGE_FILE collectstatic --dry-run --noinput &> /dev/null && RUN_COLLECTSTATIC=true
+
+    # Compile assets if collectstatic appears to be kosher.
+    if [ "$RUN_COLLECTSTATIC" ]; then
+
+        echo "       Running collectstatic..."
+        python $MANAGE_FILE collectstatic --noinput  2>&1 | sed '/^Copying/d;/^$/d;/^ /d' | indent
+
+        [ $? -ne 0 ] && {
+            echo " !     Error running 'manage.py collectstatic'. More info:"
+            echo "       http://devcenter.heroku.com/articles/django-assets"
+        }
+    else
+        echo "       Collectstatic configuration error. To debug, run:"
+        echo "       $ heroku run python $MANAGE_FILE collectstatic --noinput"
+    fi
+    echo
 fi
 
-# Compile assets if collectstatic appears to be kosher.
-echo "Copying files..." | indent
-python manage.py collectstatic --noinput | sed "/^Copying/d;/^Processing/d;/^$/d;/^ /d" | indent
+bpwatch stop collectstatic
